/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author duoc
 */
public class ControlStock extends javax.swing.JFrame {

    /**
     * Creates new form ControlStock
     */
    public ControlStock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTNActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TFNombre = new javax.swing.JTextField();
        TFTipo = new javax.swing.JTextField();
        TFDescripcion = new javax.swing.JTextField();
        TFPrecio = new javax.swing.JTextField();
        TFStock = new javax.swing.JTextField();
        BTNAgregar = new javax.swing.JButton();
        BTNVolver = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(598, 487));
        setResizable(false);
        setSize(new java.awt.Dimension(598, 487));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Descripcion", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 569, 201);

        BTNActualizar.setText("Actualizar");
        getContentPane().add(BTNActualizar);
        BTNActualizar.setBounds(470, 250, 107, 29);

        jLabel1.setText("Agregar Nuevo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 250, 93, 16);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 280, 54, 20);

        jLabel3.setText("Tipo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 310, 32, 16);

        jLabel4.setText("Descripcion:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 340, 79, 16);

        jLabel5.setText("Precio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 370, 42, 16);

        jLabel6.setText("Stock:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 410, 39, 16);
        getContentPane().add(TFNombre);
        TFNombre.setBounds(130, 280, 200, 26);
        getContentPane().add(TFTipo);
        TFTipo.setBounds(130, 310, 200, 26);
        getContentPane().add(TFDescripcion);
        TFDescripcion.setBounds(130, 340, 200, 26);
        getContentPane().add(TFPrecio);
        TFPrecio.setBounds(130, 370, 200, 26);
        getContentPane().add(TFStock);
        TFStock.setBounds(130, 410, 200, 26);

        BTNAgregar.setText("Agregar");
        getContentPane().add(BTNAgregar);
        BTNAgregar.setBounds(350, 410, 93, 29);

        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });
        getContentPane().add(BTNVolver);
        BTNVolver.setBounds(490, 410, 83, 29);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/controlstock_bg.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(598, 487));
        background.setSize(new java.awt.Dimension(598, 487));
        getContentPane().add(background);
        background.setBounds(0, 0, 598, 487);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNActualizar;
    private javax.swing.JButton BTNAgregar;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JTextField TFDescripcion;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFPrecio;
    private javax.swing.JTextField TFStock;
    private javax.swing.JTextField TFTipo;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
