/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author duoc
 */
public class Habitaciones extends javax.swing.JFrame {

    /**
     * Creates new form Habitaciones
     */
    public Habitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNHab0 = new javax.swing.JButton();
        BTNHab1 = new javax.swing.JButton();
        BTNHab2 = new javax.swing.JButton();
        BTNHab3 = new javax.swing.JButton();
        BTNHab4 = new javax.swing.JButton();
        LBHab0 = new javax.swing.JLabel();
        LBHab1 = new javax.swing.JLabel();
        LBHab2 = new javax.swing.JLabel();
        LBHab3 = new javax.swing.JLabel();
        LBHab4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNHab0.setText("Habitacion0");

        BTNHab1.setText("Habitacion1");

        BTNHab2.setText("Habitacion2");

        BTNHab3.setText("Habiaciifon3");

        BTNHab4.setText("Habitacion4");
        BTNHab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHab4ActionPerformed(evt);
            }
        });

        LBHab0.setText("-");

        LBHab1.setText("-");

        LBHab2.setText("-");

        LBHab3.setText("-");

        LBHab4.setText("-");

        jLabel1.setText("Seleccione la habitacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNHab0)
                            .addComponent(BTNHab1)
                            .addComponent(BTNHab2)
                            .addComponent(BTNHab3)
                            .addComponent(BTNHab4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBHab4)
                            .addComponent(LBHab3)
                            .addComponent(LBHab2)
                            .addComponent(LBHab1)
                            .addComponent(LBHab0)))
                    .addComponent(jLabel1))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHab0)
                    .addComponent(LBHab0))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHab1)
                    .addComponent(LBHab1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHab2)
                    .addComponent(LBHab2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHab3)
                    .addComponent(LBHab3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNHab4)
                    .addComponent(LBHab4))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNHab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHab4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNHab4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Habitaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Habitaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHab0;
    private javax.swing.JButton BTNHab1;
    private javax.swing.JButton BTNHab2;
    private javax.swing.JButton BTNHab3;
    private javax.swing.JButton BTNHab4;
    private javax.swing.JLabel LBHab0;
    private javax.swing.JLabel LBHab1;
    private javax.swing.JLabel LBHab2;
    private javax.swing.JLabel LBHab3;
    private javax.swing.JLabel LBHab4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
