/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.ControlComboBox;
import controlador.ControlLabel;
import controlador.JDBCHabitacionDAO;
import controlador.JDBCProductoDAO;
import controlador.Validacion;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import modelo.Producto;
import modelo.Reserva;

/**
 *
 * @author duoc
 */
public class Ingreso extends javax.swing.JFrame {

    /**
     * Creates new form Ingreso
     */
    static Reserva res = Reserva.getRes();
    static JDBCHabitacionDAO jdbcHab;

    public Ingreso() {
        initComponents();
        ControlComboBox.llenarCBHabitacion(CBHabDispo);
        jdbcHab = new JDBCHabitacionDAO();
        //BGModo.setSelected(RBJornada.getModel(), true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGModo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RBMomento = new javax.swing.JRadioButton();
        RBJornada = new javax.swing.JRadioButton();
        TFCantPax = new javax.swing.JTextField();
        CBHabDispo = new javax.swing.JComboBox<>();
        BTNAceptar = new javax.swing.JButton();
        BTNVolver = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        LBPreciopp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LBTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingreso");

        jLabel2.setText("Numero de personas");

        jLabel3.setText("Habitacion");

        BGModo.add(RBMomento);
        RBMomento.setText("Momento (3 hrs)");
        RBMomento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMomentoActionPerformed(evt);
            }
        });

        BGModo.add(RBJornada);
        RBJornada.setText("Jornada (12 hrs)");
        RBJornada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBJornadaActionPerformed(evt);
            }
        });

        BTNAceptar.setText("Aceptar");
        BTNAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAceptarActionPerformed(evt);
            }
        });

        BTNVolver.setText("Volver");
        BTNVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVolverActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Por Persona:");

        LBPreciopp.setText("-");

        jLabel5.setText("Total");

        LBTotal.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 343, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNAceptar)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBMomento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RBJornada))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFCantPax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBHabDispo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBPreciopp)
                    .addComponent(LBTotal))
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFCantPax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBHabDispo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBMomento)
                    .addComponent(RBJornada))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LBPreciopp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LBTotal))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNAceptar)
                    .addComponent(BTNVolver))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BTNAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAceptarActionPerformed
        // TODO add your handling code here:
        boolean pase;
        Reserva.clearRes();

        if (Validacion.validarInt(TFCantPax.getText())
                & CBHabDispo.getSelectedIndex() != 0
                & (RBJornada.isSelected()|RBMomento.isSelected())) {

            res.setOcupantes(Integer.parseInt(TFCantPax.getText()));
            res.setIdhabitacion(jdbcHab.getMap().get(CBHabDispo.getSelectedItem().toString()));
            if (RBJornada.isSelected()) {
                res.setMomento(false);
            }
            if (RBMomento.isSelected()) {
                res.setMomento(true);
            }

            //pendiente, seguramente now + 15min
            
            pase = true;

        } else {
            pase = false;
        }
        
        if (pase){
            
            new Registro(1).setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Datos incorrectos");
        }

        //
    }//GEN-LAST:event_BTNAceptarActionPerformed

    private void BTNVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVolverActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNVolverActionPerformed

    private void RBMomentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMomentoActionPerformed
        // TODO add your handling code here:
        //llamar a controlLabel 
        String nombreProd = CBHabDispo.getSelectedItem().toString().concat("_momento");
        ControlLabel.setLabelPrecioIngreso(nombreProd, TFCantPax, LBTotal, LBPreciopp);


    }//GEN-LAST:event_RBMomentoActionPerformed

    private void RBJornadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBJornadaActionPerformed
        // TODO add your handling code here:
        String nombreProd = CBHabDispo.getSelectedItem().toString().concat("_jornada");
        ControlLabel.setLabelPrecioIngreso(nombreProd, TFCantPax, LBTotal, LBPreciopp);
    }//GEN-LAST:event_RBJornadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGModo;
    private javax.swing.JButton BTNAceptar;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JComboBox<String> CBHabDispo;
    private javax.swing.JLabel LBPreciopp;
    private javax.swing.JLabel LBTotal;
    private javax.swing.JRadioButton RBJornada;
    private javax.swing.JRadioButton RBMomento;
    private javax.swing.JTextField TFCantPax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
