/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.ControlMenu_Principal;
import controlador.ControlTimer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;

/**
 *
 * @author duoc
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        
        
        //usar el constructor 
        initComponents();
        LocalDateTime pruebaLDT = LocalDateTime.now().plusHours(1);
        
        ControlMenu_Principal.llenarTablaHabitacionesDisponibles(jtableHabitacionesLibres);
        ControlMenu_Principal.llenarTablaHabitacionesOcupadas(jtableHabitacionesOcupadas);
//        ControlInfome
        // 
        
        // llenar tablas con habitaciones llenas y habitaciones vacías
        
        // habitaciones disponibles, usar 
        
        new Timer (1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jtxtReloj.setText(LocalDateTime.now().plusHours(0).format(DateTimeFormatter.ofPattern("HH:mm:ss")));
                
                // TODO:
                // Aplicar funcion CuentaReg al elemento de la tabla de cada Habitación Ocupada
                
                // jtxtReloj.setText(ControlTimer.CuentaReg(pruebaLDT));

            }

            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BTNControlStock = new javax.swing.JButton();
        BTNInformes = new javax.swing.JButton();
        BTNHab = new javax.swing.JButton();
        BTNIngreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableHabitacionesOcupadas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableHabitacionesLibres = new javax.swing.JTable();
        jtxtHeadHabitacionesOcupadas = new javax.swing.JLabel();
        jtxtHeadHabitacionesLibres = new javax.swing.JLabel();
        jtxtReloj = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(584, 461));
        setMinimumSize(new java.awt.Dimension(584, 461));
        setPreferredSize(new java.awt.Dimension(584, 461));
        setResizable(false);
        setSize(new java.awt.Dimension(584, 461));
        getContentPane().setLayout(null);

        jLabel2.setText("Hotel Open Mind");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 106, 16);

        BTNControlStock.setText("Control Stock");
        BTNControlStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNControlStockActionPerformed(evt);
            }
        });
        getContentPane().add(BTNControlStock);
        BTNControlStock.setBounds(400, 125, 120, 50);

        BTNInformes.setText("Informes");
        BTNInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInformesActionPerformed(evt);
            }
        });
        getContentPane().add(BTNInformes);
        BTNInformes.setBounds(400, 63, 120, 50);

        BTNHab.setText("Pedidos");
        BTNHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHabActionPerformed(evt);
            }
        });
        getContentPane().add(BTNHab);
        BTNHab.setBounds(400, 191, 120, 50);

        BTNIngreso.setText("Ingreso");
        BTNIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIngresoActionPerformed(evt);
            }
        });
        getContentPane().add(BTNIngreso);
        BTNIngreso.setBounds(400, 253, 120, 50);

        jtableHabitacionesOcupadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Habitacion", "Número Pasajeros", "Última Acción", "Tiempo Restante"
            }
        ));
        jScrollPane1.setViewportView(jtableHabitacionesOcupadas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 356, 128);

        jtableHabitacionesLibres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Habitación"
            }
        ));
        jScrollPane3.setViewportView(jtableHabitacionesLibres);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 220, 356, 200);

        jtxtHeadHabitacionesOcupadas.setText("Información Habitaciones Ocupadas");
        getContentPane().add(jtxtHeadHabitacionesOcupadas);
        jtxtHeadHabitacionesOcupadas.setBounds(20, 50, 228, 16);

        jtxtHeadHabitacionesLibres.setText("Información Habitaciones Libres");
        getContentPane().add(jtxtHeadHabitacionesLibres);
        jtxtHeadHabitacionesLibres.setBounds(20, 200, 204, 16);

        jtxtReloj.setText("jLabel3");
        getContentPane().add(jtxtReloj);
        jtxtReloj.setBounds(400, 20, 80, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu_principal_bg.png"))); // NOI18N
        background.setSize(new java.awt.Dimension(584, 461));
        getContentPane().add(background);
        background.setBounds(0, 0, 584, 461);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHabActionPerformed
        // TODO add your handling code here:
        new Habitaciones().setVisible(true);
    }//GEN-LAST:event_BTNHabActionPerformed

    private void BTNControlStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNControlStockActionPerformed
        // TODO add your handling code here:
        new ControlStock().setVisible(true);
        
    }//GEN-LAST:event_BTNControlStockActionPerformed

    private void BTNInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInformesActionPerformed
        // TODO add your handling code here:
        new Informes().setVisible(true);
    }//GEN-LAST:event_BTNInformesActionPerformed

    private void BTNIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIngresoActionPerformed
        // TODO add your handling code here:
        new Ingreso().setVisible(true);
    }//GEN-LAST:event_BTNIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        
        
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
        
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNControlStock;
    private javax.swing.JButton BTNHab;
    private javax.swing.JButton BTNInformes;
    private javax.swing.JButton BTNIngreso;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtableHabitacionesLibres;
    private javax.swing.JTable jtableHabitacionesOcupadas;
    private javax.swing.JLabel jtxtHeadHabitacionesLibres;
    private javax.swing.JLabel jtxtHeadHabitacionesOcupadas;
    private static javax.swing.JLabel jtxtReloj;
    // End of variables declaration//GEN-END:variables
}
