/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import controlador.ControlComboBox;
import controlador.ControlFormulario;
import controlador.JDBCPaxDAO;
import controlador.Validacion;
import modelo.FormularioRegistroPax;
import modelo.Pax;
import modelo.Reserva;

/**
 *
 * @author duoc
 */
public class Registro extends javax.swing.JFrame {
    int paxActual;
    JDBCPaxDAO jdbcpax = new JDBCPaxDAO();
    Pax pasajero = Pax.getPax();
    FormularioRegistroPax frp;
    

    /** Creates new form Registro
     * @param paxActual 
     * 
     */
    public Registro(int paxActual) {
        
        this.paxActual = paxActual;
        initComponents();
        Reserva res = Reserva.getRes();
        LBTotal.setText(String.valueOf(res.getOcupantes()));
        LBActual.setText(String.valueOf(this.paxActual));
        if (this.paxActual == 1) {
            LBPasajeroPrincipal.setVisible(true);
            BTNSorteo.setVisible(true);
        } else {
            LBPasajeroPrincipal.setVisible(false);
            BTNSorteo.setVisible(false);
        }
        
        Pax.clearPax();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LBActual = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LBTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFRut = new javax.swing.JTextField();
        TFNombre = new javax.swing.JTextField();
        TFApellidoPat = new javax.swing.JTextField();
        TFApellidoMat = new javax.swing.JTextField();
        CBSexo = new javax.swing.JComboBox<>();
        CBFechaDia = new javax.swing.JComboBox<>();
        CBFechaMes = new javax.swing.JComboBox<>();
        CBFechaAño = new javax.swing.JComboBox<>();
        TFNac = new javax.swing.JTextField();
        BTNSorteo = new javax.swing.JButton();
        BTNIngresar = new javax.swing.JButton();
        BTNCancelar = new javax.swing.JButton();
        BTNVolver = new javax.swing.JButton();
        LBPasajeroPrincipal = new javax.swing.JLabel();
        BTNVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registro de pasajeros");

        jLabel2.setText("Rut:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido Paterno:");

        LBActual.setText("-");

        jLabel6.setText("/");

        LBTotal.setText("-");

        jLabel5.setText("Sexo:");

        jLabel7.setText("Fecha Nacimiento:");

        jLabel8.setText("Nacionalidad:");

        jLabel9.setText("Apellido Materno:");

        TFRut.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TFRutComponentAdded(evt);
            }
        });
        TFRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFRutActionPerformed(evt);
            }
        });

        CBFechaMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        CBFechaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFechaMesActionPerformed(evt);
            }
        });

        CBFechaAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930" }));
        CBFechaAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFechaAñoActionPerformed(evt);
            }
        });

        BTNSorteo.setText("SORTEO!");

        BTNIngresar.setText("Ingresar");
        BTNIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNIngresarActionPerformed(evt);
            }
        });

        BTNCancelar.setText("Cancelar");

        BTNVolver.setText("Anterior");

        LBPasajeroPrincipal.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        LBPasajeroPrincipal.setText("PASAJERO PRINCIPAL");

        BTNVerificar.setText("Verificar pax");
        BTNVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(LBPasajeroPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBTotal)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFApellidoPat)
                    .addComponent(TFApellidoMat)
                    .addComponent(TFRut)
                    .addComponent(TFNombre)
                    .addComponent(TFNac)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBFechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CBFechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNVerificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNSorteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNIngresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LBActual)
                    .addComponent(jLabel6)
                    .addComponent(LBTotal)
                    .addComponent(LBPasajeroPrincipal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TFRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BTNVerificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TFApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(CBFechaDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBFechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TFNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BTNSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNIngresar)
                    .addComponent(BTNCancelar)
                    .addComponent(BTNVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNIngresarActionPerformed
        // TODO add your handling code here:
        /* jdbcpax.
        paxActual++;
        new Registro(paxActual).setVisible(true);
        dispose();*/
    }//GEN-LAST:event_BTNIngresarActionPerformed

    private void TFRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFRutActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_TFRutActionPerformed

    private void BTNVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVerificarActionPerformed
        // TODO add your handling code here:
        frp = FormularioRegistroPax.getForm(TFRut, TFNombre, TFApellidoPat, TFApellidoMat, TFNac, CBFechaDia, CBFechaMes, CBFechaAño, CBSexo);
        Pax.clearPax();
         if (Validacion.validarInt(TFRut.getText())){
            int rut = Integer.parseInt(TFRut.getText());
            if (jdbcpax.existe(rut)){
               
               pasajero = jdbcpax.selectRead(rut);
               
               ControlFormulario.llenarFormularioRegistro(pasajero, frp);
               
            }
            
                
        }
        
        
    }//GEN-LAST:event_BTNVerificarActionPerformed

    private void TFRutComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TFRutComponentAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TFRutComponentAdded

    private void CBFechaAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFechaAñoActionPerformed
        // TODO add your handling code here:
        int mesSeleccionado = CBFechaMes.getSelectedIndex();
        ControlComboBox.llenarCBFechaNacimientoRegistro(mesSeleccionado, Integer.valueOf(CBFechaAño.getSelectedItem().toString()),CBFechaDia);
  
        
    }//GEN-LAST:event_CBFechaAñoActionPerformed

    private void CBFechaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFechaMesActionPerformed
        // TODO add your handling code here:
        int mesSeleccionado = CBFechaMes.getSelectedIndex();
        ControlComboBox.llenarCBFechaNacimientoRegistro(mesSeleccionado, Integer.valueOf(CBFechaAño.getSelectedItem().toString()),CBFechaDia);
    }//GEN-LAST:event_CBFechaMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
        new Registro().setVisible(true);
        }
        });s*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCancelar;
    private javax.swing.JButton BTNIngresar;
    private javax.swing.JButton BTNSorteo;
    private javax.swing.JButton BTNVerificar;
    private javax.swing.JButton BTNVolver;
    private javax.swing.JComboBox<String> CBFechaAño;
    private javax.swing.JComboBox<String> CBFechaDia;
    private javax.swing.JComboBox<String> CBFechaMes;
    private javax.swing.JComboBox<String> CBSexo;
    private javax.swing.JLabel LBActual;
    private javax.swing.JLabel LBPasajeroPrincipal;
    private javax.swing.JLabel LBTotal;
    private javax.swing.JTextField TFApellidoMat;
    private javax.swing.JTextField TFApellidoPat;
    private javax.swing.JTextField TFNac;
    private javax.swing.JTextField TFNombre;
    private javax.swing.JTextField TFRut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
