/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import controlador.ControlDescuento;
import controlador.ControlLabel;
import controlador.JDBCReservaDAO;
import controlador.JDBCHabitacionDAO;
import controlador.JDBCPaxDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.ArrayRuts;
import modelo.Habitacion;
import modelo.Pax;
import modelo.Reserva;

/**
 *
 * @author proyetco
 */
public class ResumenReserva extends javax.swing.JFrame {
    Reserva res = Reserva.getRes();
    Pax pasajero = Pax.getPax();
    JDBCPaxDAO jdbcpax = new JDBCPaxDAO();
    JDBCHabitacionDAO jdbchab = new JDBCHabitacionDAO();
    Habitacion[] h;
    JDBCReservaDAO jdbcReservaDAO = new JDBCReservaDAO();
    

    /**
     * Creates new form Cobro
     */
    public ResumenReserva() {
        initComponents();
        Pax.clearPax();
        h = jdbchab.selectAll();
        pasajero = jdbcpax.selectRead(res.getRut());
        LBPaxPpal.setText(pasajero.getNombre()+" "+pasajero.getApellidoPat());
        //LBPaxPpal.setText(String.valueOf(pasajero.getRut()));
        LBOcupantes.setText(res.getOcupantes().toString());
        LBHab.setText(jdbchab.selectNombreHab(res.getIdhabitacion()));
        ControlLabel.setLabelPrecioPorPersona(res, LBPreciopp);
        LBDesc.setText(ControlDescuento.getDescuento(res.getOcupantes()));        
        ControlLabel.setPrecioSubTotal(res, LBDescpp);
        ControlLabel.setPrecioTotal(res, LBTotal, ControlDescuento.getMultiplicadorDescuento(res.getOcupantes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTNCobrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TFPago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        LBVuelto = new javax.swing.JLabel();
        LBPaxPpal = new javax.swing.JLabel();
        LBOcupantes = new javax.swing.JLabel();
        LBHab = new javax.swing.JLabel();
        LBPreciopp = new javax.swing.JLabel();
        LBDesc = new javax.swing.JLabel();
        LBDescpp = new javax.swing.JLabel();
        LBTotal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(314, 440));
        setResizable(false);
        setSize(new java.awt.Dimension(314, 440));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Resumen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setText("Pasajero Principal:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Total de ocupantes:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Habitacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setText("Precio por persona:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel6.setText("Descuento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel7.setText("Descuento por persona:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setText("Total:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        BTNCobrar.setText("Pagar");
        BTNCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCobrarActionPerformed(evt);
            }
        });
        getContentPane().add(BTNCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        jLabel9.setText("Pago:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        TFPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPagoActionPerformed(evt);
            }
        });
        getContentPane().add(TFPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 96, -1));

        jLabel10.setText("Vuelto:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        LBVuelto.setText("-");
        getContentPane().add(LBVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 80, -1));

        LBPaxPpal.setText("-");
        getContentPane().add(LBPaxPpal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

        LBOcupantes.setText("-");
        getContentPane().add(LBOcupantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, -1));

        LBHab.setText("-");
        getContentPane().add(LBHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, -1));

        LBPreciopp.setText("-");
        getContentPane().add(LBPreciopp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, -1));

        LBDesc.setText("-");
        getContentPane().add(LBDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 80, -1));

        LBDescpp.setText("-");
        getContentPane().add(LBDescpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, -1));

        LBTotal.setText("-");
        getContentPane().add(LBTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/resumen_reserva_bg.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPagoActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(LBTotal.getText());
        int pago = Integer.parseInt(TFPago.getText());
        String vuelto = String.valueOf(pago-total);
        LBVuelto.setText(vuelto);
    }//GEN-LAST:event_TFPagoActionPerformed

    private void BTNCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCobrarActionPerformed
        // TODO add your handling code here:
        // el problema radicaba en que el id de la habitacion es uno mayor a el indice de la habitacion[]
        h[res.getIdhabitacion()-1].setOcupado(true);
        h[res.getIdhabitacion()-1].setRutPaxOcupante(res.getRut());

        
        jdbchab.updateOcupado(h[res.getIdhabitacion()-1]);
        
        //JOptionPane.showMessageDialog(null, res.getRut() +" "+ h[res.getIdhabitacion()].getRutPaxOcupante());
        jdbcReservaDAO.insert(res);
        
        
        // ingresar a tabla registro pasajaros
        ArrayList<Integer> ar = ArrayRuts.getArray();
        
        jdbcReservaDAO.insertarArrayRutsRegistroPax(ar,res.getIdJornada());

        
        dispose();
        new Menu_Principal().setVisible(true);
        //agregar a bbdd lo correspondiente a la habitacion reserva_has_producto
        
        // funcion DAO prodHasRes donde se pueda insertar(int idprod,int idres,int cantidad, int precio , localdatetime.now());
        //con Producto se recupera el precio unitario y ocupantes es cantidad
        //en caso de premiado deberia haber algun boleano pero no esta implementado aun.
        
        
        
        
     
    }//GEN-LAST:event_BTNCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumenReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumenReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCobrar;
    private javax.swing.JLabel LBDesc;
    private javax.swing.JLabel LBDescpp;
    private javax.swing.JLabel LBHab;
    private javax.swing.JLabel LBOcupantes;
    private javax.swing.JLabel LBPaxPpal;
    private javax.swing.JLabel LBPreciopp;
    private javax.swing.JLabel LBTotal;
    private javax.swing.JLabel LBVuelto;
    private javax.swing.JTextField TFPago;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
